services:
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - nc_gold
      - nc_silver
      - nc_copper
      - nc_local

  nc_local:
    build: ./server

  nc_gold:
    build: ./server  

  nc_silver:
    build: ./server  

  nc_copper:
    build: ./server  
